version: "3.8"

services:
    # Conteneur MYSQL 
    db:
        image: mysql
        container_name: docker_mysql
        restart: always
        volumes: 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks: 
            - dev

    # Conteneur PHPMYADMIN
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        container_name: docker_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
        ports:
            - "8080:80"
        networks:
            - dev
            
    # Conteneur php + apache
    www:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: docker_www
        ports:
            - "8082:80"
        volumes: 
            - ./php/vhosts:/etc/apache2/sites-available
            - ./projet_symfony:/var/www/html 
        restart: always
        networks:
            - dev

networks: 
    dev:

volumes: 
    db-data:
