apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort  # This exposes the service via a NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007  # Specify a port in the NodePort range (30000-32767)
  selector:
    app: phpmyadmin

