version: '3.8'

services:
  php7-service:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: solmos034/php7:latest
    volumes:
      - ./src/my_project:/var/www/html/my_project
    expose:
      - 9000
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure

  nginx-service:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: solmos034/nginx7:latest
    volumes:
      - ./src/my_project:/var/www/html/my_project
    ports:
      - "8086:80"
    depends_on:
      - php7-service
    networks:
      - app-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
      restart_policy:
        condition: on-failure
   #Conteneur MYSQL 
  db:
        image: mysql
        container_name: docker_mysql
        restart: always
        volumes: 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks: 
            - app-network
    #Conteneur PHPMYADMIN
  phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        container_name: docker_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
        ports:
            - "8087:80"
        networks:
            - app-network

networks:
  app-network:
    driver: bridge

volumes: 
    db-data:
