apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: ${{ secrets.DOCKERHUB_USERNAME }}/symfony_project01:php-latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /var/www
      volumes:
      - name: www-data
        persistentVolumeClaim:
          claimName: www-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
