apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-symfony-example.fullname" . }}
  labels:
{{ include "k8s-symfony-example.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-symfony-example.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8s-symfony-example.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: www
          image: solmos034/app_update:docker-projet-www
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: apache-config
              mountPath: /etc/apache2/sites-available/vhosts.conf
              subPath: vhosts.conf
            - name: project-code
              mountPath: /var/www/projet_symfony/projet_symfony
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /public/index.php
              port: http
          readinessProbe:
            httpGet:
              path: /public/index.php
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: apache-config
          configMap:
            name: apache-config
        - name: project-code
          emptyDir: {}