# CD WORKFLOW
name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start

      - name: Create MySQL deployment
        run: kubectl create -f ./resources/kubernetes/deployments/mysql.yaml

      - name: Create phpMyAdmin deployment
        run: kubectl create -f ./resources/kubernetes/deployments/phpmyadmn.yaml

      - name: Create local deployment
        run: kubectl create -f ./resources/kubernetes/deployments/local-deployment.yaml

      - name: Get Pods
        run: kubectl get pods

      - name: Get Services
        run: kubectl get svc  # List all services to confirm

      - name: Get NGINX Service URL
        run: |
          NGINX_URL=$(minikube service nginx-service --url || echo "Service not found")
          echo "NGINX Service URL: $NGINX_URL"

      - name: Get phpMyAdmin Service URL
        run: |
          PHPMYADMIN_URL=$(minikube service phpmyadmin --url || echo "Service not found")
          echo "phpMyAdmin Service URL: $PHPMYADMIN_URL"
