name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: medikoo/minikube-action@v1
      with:
        minikube_version: '1.23.0'  # Spécifiez la version de Minikube souhaitée

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.23.0

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/pvc.yml
        kubectl apply -f k8s/database.yml
        kubectl apply -f k8s/app.yml

    - name: Wait for MySQL to be ready
      run: |
        kubectl rollout status deployment/mysql --timeout=120s

    - name: Wait for PHP Apache to be ready
      run: |
        kubectl rollout status deployment/php-apache --timeout=120s

    - name: Verify MySQL Service
      run: |
        kubectl get service mysql

    - name: Verify PHP Apache Service
      run: |
        kubectl get service php-apache

    - name: Output Deployment Status
      run: |
        kubectl get deployments
        kubectl get pods
