name: CD Workflow

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          minikube start

      - name: Create MySQL Deployment
        run: kubectl create -f ./resources/kubernetes/deployments/mysql.yaml

      - name: Create PHPMyAdmin Deployment
        run: kubectl create -f ./resources/kubernetes/deployments/phpmyadmn.yaml

      - name: Create Local Service
        run: kubectl create -f ./resources/kubernetes/services/local-service.yaml

      - name: Create PHP7 and NGINX Deployments
        run: kubectl create -f ./resources/kubernetes/deployments/local-deployment.yaml

      - name: Wait for services and pods to be ready
        run: |
          echo "Waiting for services and pods to be ready..."
          for i in {1..60}; do
            # Vérifier si les services nginx et phpmyadmin sont disponibles
            if kubectl get svc nginx-service && kubectl get svc phpmyadmin; then
              # Vérifier si les pods sont prêts (Running ou Completed)
              PODS_READY=$(kubectl get pods --no-headers | grep -E 'Running|Completed' | wc -l)
              if [ "$PODS_READY" -ge 2 ]; then
                echo "Services and pods are ready!"
                exit 0
              fi
            fi
            echo "Waiting for services and pods... ($i/60)"
            sleep 5
          done

          # Si après 5 minutes, les pods ne sont pas prêts, afficher un message d'erreur et quitter avec une erreur
          echo "Services or pods did not become ready within the expected time."
          kubectl get pods
          exit 1

      - name: Display Pods
        run: kubectl get pods

      - name: Get NGINX Service URL
        run: |
          NGINX_URL=$(minikube service nginx-service --url || echo "Service not found")
          echo "NGINX Service URL: $NGINX_URL"

      - name: Get PHPMyAdmin Service URL
        run: |
          PHP_MYADMIN_URL=$(minikube service phpmyadmin --url || echo "Service not found")
          echo "PHPMyAdmin Service URL: $PHP_MYADMIN_URL"
