name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        run: |
          minikube start

      - name: Create MySQL Deployment
        run: kubectl create -f ./resources/kubernetes/deployments/mysql.yaml

      - name: Create phpMyAdmin Deployment
        run: kubectl create -f ./resources/kubernetes/deployments/phpmyadmn.yaml

      - name: Create NGINX Service
        run: kubectl create -f ./resources/kubernetes/services/local-service.yaml

      - name: Create NGINX Deployment
        run: kubectl create -f ./resources/kubernetes/deployments/local-deployment.yaml

      - name: List all Services
        run: kubectl get svc

      - name: Get NGINX Service URL
        run: |
          NGINX_URL=$(minikube service nginx-service --url || echo "Service not found")
          echo "NGINX Service URL: $NGINX_URL"

      - name: Get phpMyAdmin Service URL
        run: |
          PMA_URL=$(minikube service phpmyadmin --url || echo "Service not found")
          echo "phpMyAdmin Service URL: $PMA_URL"
