# CI WORKFLOW  
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose services
        run: |
          docker-compose up -d

      - name: Build and push PHP image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/php7:latest ./resources/docker/php
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/php7:latest

      - name: Build and push Nginx image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx7:latest ./resources/docker/nginx
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx7:latest

      - name: Commit and push MySQL container image
        run: |
          CONTAINER_ID=$(docker-compose ps -q db)
          docker commit $CONTAINER_ID ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest

      - name: Commit and push phpMyAdmin container image
        run: |
          CONTAINER_ID=$(docker-compose ps -q phpmyadmin)
          docker commit $CONTAINER_ID ${{ secrets.DOCKERHUB_USERNAME }}/phpmyadmin:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/phpmyadmin:latest
