# CI WORKFLOW
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PHP image
        uses: docker/build-push-action@v2
        with:
          context: ./php
          file: ./php/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/symfony_project01:php-latest

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose services
        run: |
          docker-compose up -d

      - name: Commit and push MySQL image
        run: |
          CONTAINER_ID=$(docker-compose ps -q db)
          docker commit $CONTAINER_ID ${{ secrets.DOCKERHUB_USERNAME }}/symfony_project01:mysql-latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/symfony_project01:mysql-latest

      - name: Commit and push phpMyAdmin image
        run: |
          CONTAINER_ID=$(docker-compose ps -q phpmyadmin)
          docker commit $CONTAINER_ID ${{ secrets.DOCKERHUB_USERNAME }}/symfony_project01:phpmyadmin-latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/symfony_project01:phpmyadmin-latest
