# CI WORKFLOW
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push PHP image from Dockerfile
      - name: Build and push PHP image
        uses: docker/build-push-action@v2
        with:
          context: ./resources/docker/php
          file: ./resources/docker/php/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php7:latest

      # Build and push NGINX image from Dockerfile
      - name: Build and push NGINX image
        uses: docker/build-push-action@v2
        with:
          context: ./resources/docker/nginx
          file: ./resources/docker/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx7:latest

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Start services using Docker Compose
      - name: Start Docker Compose services
        run: |
          docker-compose -f ./resources/docker/docker-compose.yml up -d

      # Commit and push MySQL container image
      - name: Commit and push MySQL image
        run: |
          CONTAINER_ID=$(docker-compose -f ./resources/docker/docker-compose.yml ps -q db)
          docker commit $CONTAINER_ID ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql:latest

      # Commit and push phpMyAdmin container image
      - name: Commit and push phpMyAdmin image
        run: |
          CONTAINER_ID=$(docker-compose -f ./resources/docker/docker-compose.yml ps -q phpmyadmin)
          docker commit $CONTAINER_ID ${{ secrets.DOCKERHUB_USERNAME }}/phpmyadmin:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/phpmyadmin:latest
